name: bonsai

on:
  workflow_run:
    workflows: ["goreleaser"]
    types:
      - completed

jobs:
  bonsai-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    steps:
      - name: request bonsai rebuild
        continue-on-error: true
        run: >
          curl -v -XPOST
          -H "X-GitHub-Token: ${{ secrets.GITHUB_TOKEN }}"
          --url "https://bonsai.sensu.io/assets/${{ github.repository }}/build"

